apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: musicxshare
  name: musicxshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musicxshare
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: musicxshare
    spec:
      containers:
      - image: IMAGE_PLACEHOLDER
        name: musicshare
        resources: {}
status: {}
