apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: musicxshare
  name: musicxshare
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: musicxshare
  type: LoadBalancer
status:
  loadBalancer: {}
